modLoader="javafml"
loaderVersion="[51,)"
license="${mod_license}"
issueTrackerURL="https://github.com/bh679/pigmanvillagers-mc/issues"

[[mods]]
modId="pigmanvillagers"
version="${version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
displayURL="https://github.com/bh679/pigmanvillagers-mc"

[[dependencies.pigmanvillagers]]
    modId="forge"
    mandatory=true
    versionRange="[51,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pigmanvillagers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="pigmanvillagers.mixins.json"
